# Generated by Django 4.2.12 on 2024-09-27 18:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_withdrawal_account_number_withdrawal_bank_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cryptocoin',
            name='name',
            field=models.CharField(),
        ),
    ]
