# Generated by Django 4.2.12 on 2024-09-27 19:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_alter_cryptocoin_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cryptocoin',
            name='wallet_address',
            field=models.CharField(),
        ),
    ]
